### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by jomei** [EvaSerenity/url_shortener#1]
Привет! посмотрел твое задание, вот фидбек:
1. проект инициирован с кучей неиспользуемого мусора, хотя у тебя api-only приложение
2. коннекшен к редису создается на каждый запрос.
3. валидация параметров отсутствует
4. тесты отстутсвуют

В целом, хорошей тоном считается добавлять README с описанием API, а также задеплоить на какую нибудь Heroku демо.

Исправления можно оформить отдельным PR, пинганув в нем меня.

**Comment by EvaSerenity** [comment]
Привет, на самом деле это неработающий прототип, о чем я написала в письме и добавила в комментарии в контроллере.
Тесты локально у меня есть, но не закомичены, потому что они падают.
По поводу остального - хотелось сначала добиться корректной работы, а затем уже добавлять валидацию и прочее
